# Generated by Django 3.2.6 on 2021-09-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throughmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
