# Generated by Django 3.2.6 on 2021-11-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211117_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='Uncategorized', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
    ]
