# Generated by Django 3.2.6 on 2021-09-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Date'),
        ),
    ]
