# Generated by Django 3.2.6 on 2021-11-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='status',
            field=models.CharField(default='Active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
    ]
