# Generated by Django 3.2.6 on 2021-11-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211130_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='status',
            field=models.CharField(default='Active', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
