# Generated by Django 3.2.6 on 2021-11-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_po_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
